export interface ResourceLink {
  id: string;
  name: string;
  tagline: string;
  url: string;
  category: ResourceCategory;
  tags: string[];
  free: boolean;
  highlight?: string;
}

export type ResourceCategory =
  | "apis"
  | "frameworks"
  | "agents"
  | "infrastructure"
  | "mcp"
  | "evals"
  | "communities"
  | "research";

export interface ResourceCategoryMeta {
  id: ResourceCategory;
  label: string;
  icon: string;
  desc: string;
  color: string;
}

export const RESOURCE_CATEGORIES: ResourceCategoryMeta[] = [
  { id: "apis",           label: "APIs & Model Access",       icon: "⚡", color: "#9F8CFF", desc: "LLM providers and inference APIs" },
  { id: "frameworks",     label: "Developer Frameworks",      icon: "🧱", color: "#5EEAD4", desc: "SDKs and libraries for building AI apps" },
  { id: "agents",         label: "Agents & Orchestration",    icon: "🤖", color: "#F08CA8", desc: "Multi-agent frameworks and workflows" },
  { id: "infrastructure", label: "Infrastructure",            icon: "🗄️", color: "#E8C089", desc: "Vector stores, local inference, and hosting" },
  { id: "mcp",            label: "MCP & Integrations",        icon: "🔌", color: "#6EE7A0", desc: "Model Context Protocol servers and connectors" },
  { id: "evals",          label: "Evals & Benchmarks",        icon: "📊", color: "#B6A6FF", desc: "Testing, evaluation, and quality tools" },
  { id: "communities",    label: "Communities",               icon: "🌐", color: "#F4D06F", desc: "Forums, Discord servers, and news feeds" },
  { id: "research",       label: "Research & Papers",         icon: "📖", color: "#8FE3D2", desc: "Academic papers, blogs, and technical writing" },
];

export const RESOURCES: ResourceLink[] = [
  // ── APIs & Model Access ───────────────────────────────────────────────────
  {
    id: "anthropic-api",
    name: "Anthropic API",
    tagline: "Access Claude models via API",
    url: "https://console.anthropic.com",
    category: "apis",
    tags: ["Claude", "Anthropic", "API"],
    free: false,
    highlight: "Direct access to Claude Haiku, Sonnet, and Opus with prompt caching and batch processing",
  },
  {
    id: "openai-api",
    name: "OpenAI Platform",
    tagline: "GPT-4, o3, and embeddings",
    url: "https://platform.openai.com",
    category: "apis",
    tags: ["GPT", "OpenAI", "API"],
    free: false,
    highlight: "Access GPT-4o, o3-mini, DALL-E 3, Whisper, and embedding models",
  },
  {
    id: "google-ai-studio",
    name: "Google AI Studio",
    tagline: "Gemini models with generous free tier",
    url: "https://aistudio.google.com",
    category: "apis",
    tags: ["Gemini", "Google", "API"],
    free: true,
    highlight: "Free tier includes Gemini 2.0 Flash with 1M token context window",
  },
  {
    id: "groq",
    name: "Groq",
    tagline: "Ultra-fast LLM inference",
    url: "https://console.groq.com",
    category: "apis",
    tags: ["Groq", "inference", "fast"],
    free: true,
    highlight: "LPU-based hardware delivers industry-leading inference speeds on open models",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    tagline: "Unified API for 200+ models",
    url: "https://openrouter.ai",
    category: "apis",
    tags: ["unified", "API", "routing"],
    free: false,
    highlight: "Single OpenAI-compatible endpoint for Claude, GPT, Gemini, Llama, and more",
  },
  {
    id: "together-ai",
    name: "Together AI",
    tagline: "Open-source model inference and fine-tuning",
    url: "https://www.together.ai",
    category: "apis",
    tags: ["open-source", "fine-tuning", "API"],
    free: false,
    highlight: "Run and fine-tune Llama, Mistral, and other open models with a simple API",
  },
  {
    id: "replicate",
    name: "Replicate",
    tagline: "Run open-source models in the cloud",
    url: "https://replicate.com",
    category: "apis",
    tags: ["open-source", "images", "audio"],
    free: false,
    highlight: "One-line API for thousands of community models including Stable Diffusion and Flux",
  },
  {
    id: "huggingface-inference",
    name: "Hugging Face Inference",
    tagline: "Hosted inference for HF models",
    url: "https://huggingface.co/inference-api",
    category: "apis",
    tags: ["HuggingFace", "open-source", "API"],
    free: true,
    highlight: "Free serverless inference on 100,000+ models from the HF Hub",
  },

  // ── Developer Frameworks ──────────────────────────────────────────────────
  {
    id: "langchain",
    name: "LangChain",
    tagline: "Python/JS framework for LLM apps",
    url: "https://python.langchain.com",
    category: "frameworks",
    tags: ["Python", "JavaScript", "framework"],
    free: true,
    highlight: "Composable chains, retrieval, agents, and integrations for every major LLM",
  },
  {
    id: "llamaindex",
    name: "LlamaIndex",
    tagline: "Data framework for LLM applications",
    url: "https://www.llamaindex.ai",
    category: "frameworks",
    tags: ["RAG", "Python", "data"],
    free: true,
    highlight: "Best-in-class RAG pipelines with support for 100+ data source connectors",
  },
  {
    id: "vercel-ai-sdk",
    name: "Vercel AI SDK",
    tagline: "TypeScript toolkit for AI-powered UIs",
    url: "https://sdk.vercel.ai",
    category: "frameworks",
    tags: ["TypeScript", "React", "streaming"],
    free: true,
    highlight: "Unified API with streaming, tool calling, and structured outputs for all major providers",
  },
  {
    id: "anthropic-sdk",
    name: "Anthropic SDK",
    tagline: "Official Python and TypeScript SDKs",
    url: "https://github.com/anthropics/anthropic-sdk-python",
    category: "frameworks",
    tags: ["Python", "TypeScript", "Anthropic"],
    free: true,
    highlight: "First-party SDK with full type safety, streaming, tool use, and prompt caching support",
  },
  {
    id: "pydantic-ai",
    name: "Pydantic AI",
    tagline: "Agent framework from the Pydantic team",
    url: "https://ai.pydantic.dev",
    category: "frameworks",
    tags: ["Python", "agents", "typed"],
    free: true,
    highlight: "Type-safe agent framework with dependency injection and model-agnostic design",
  },
  {
    id: "instructor",
    name: "Instructor",
    tagline: "Structured outputs from LLMs via Pydantic",
    url: "https://python.useinstructor.com",
    category: "frameworks",
    tags: ["Python", "structured", "validation"],
    free: true,
    highlight: "Forces LLM responses into validated Pydantic models with automatic retry on failure",
  },

  // ── Agents & Orchestration ────────────────────────────────────────────────
  {
    id: "crewai",
    name: "CrewAI",
    tagline: "Multi-agent role-based framework",
    url: "https://www.crewai.com",
    category: "agents",
    tags: ["multi-agent", "Python", "roles"],
    free: true,
    highlight: "Assign roles to agents and let them collaborate on complex tasks autonomously",
  },
  {
    id: "langgraph",
    name: "LangGraph",
    tagline: "Stateful multi-actor workflows",
    url: "https://langchain-ai.github.io/langgraph",
    category: "agents",
    tags: ["graph", "stateful", "Python"],
    free: true,
    highlight: "Build cyclic, stateful agent workflows as graphs with fine-grained control",
  },
  {
    id: "autogen",
    name: "AutoGen",
    tagline: "Multi-agent conversation framework by Microsoft",
    url: "https://microsoft.github.io/autogen",
    category: "agents",
    tags: ["Microsoft", "multi-agent", "Python"],
    free: true,
    highlight: "Customizable conversational agents that work together to solve tasks",
  },
  {
    id: "composio",
    name: "Composio",
    tagline: "100+ managed tools for AI agents",
    url: "https://composio.dev",
    category: "agents",
    tags: ["tools", "integrations", "agents"],
    free: true,
    highlight: "Pre-built integrations with GitHub, Slack, Gmail, Jira, and 100+ apps for agents",
  },
  {
    id: "smolagents",
    name: "smolagents",
    tagline: "Minimal agent library by HuggingFace",
    url: "https://huggingface.co/docs/smolagents",
    category: "agents",
    tags: ["HuggingFace", "lightweight", "Python"],
    free: true,
    highlight: "Minimal ~1,000 line codebase for code-first agents that write and execute Python",
  },

  // ── Infrastructure ────────────────────────────────────────────────────────
  {
    id: "ollama",
    name: "Ollama",
    tagline: "Run LLMs locally on your machine",
    url: "https://ollama.ai",
    category: "infrastructure",
    tags: ["local", "open-source", "macOS"],
    free: true,
    highlight: "One command to run Llama, Mistral, Gemma, and 100+ models locally with GPU support",
  },
  {
    id: "vllm",
    name: "vLLM",
    tagline: "High-throughput LLM serving engine",
    url: "https://vllm.ai",
    category: "infrastructure",
    tags: ["serving", "Python", "performance"],
    free: true,
    highlight: "PagedAttention memory management for up to 24× throughput improvement over HuggingFace",
  },
  {
    id: "pinecone",
    name: "Pinecone",
    tagline: "Managed vector database",
    url: "https://www.pinecone.io",
    category: "infrastructure",
    tags: ["vector DB", "RAG", "managed"],
    free: true,
    highlight: "Serverless vector DB with built-in hybrid search (dense + sparse) for RAG applications",
  },
  {
    id: "qdrant",
    name: "Qdrant",
    tagline: "Open-source vector similarity engine",
    url: "https://qdrant.tech",
    category: "infrastructure",
    tags: ["vector DB", "open-source", "Rust"],
    free: true,
    highlight: "High-performance Rust-based vector database with filtering and payload support",
  },
  {
    id: "weaviate",
    name: "Weaviate",
    tagline: "AI-native vector database",
    url: "https://weaviate.io",
    category: "infrastructure",
    tags: ["vector DB", "open-source", "GraphQL"],
    free: true,
    highlight: "Built-in vectorization modules for text, images, and multimodal data",
  },
  {
    id: "chroma",
    name: "ChromaDB",
    tagline: "Open-source embedding database",
    url: "https://www.trychroma.com",
    category: "infrastructure",
    tags: ["vector DB", "open-source", "Python"],
    free: true,
    highlight: "Simplest vector DB to get started with — runs locally in pure Python, no setup needed",
  },

  // ── MCP & Integrations ────────────────────────────────────────────────────
  {
    id: "mcp",
    name: "Model Context Protocol",
    tagline: "Open standard for AI-to-tool connections",
    url: "https://modelcontextprotocol.io",
    category: "mcp",
    tags: ["MCP", "standard", "Anthropic"],
    free: true,
    highlight: "Open protocol by Anthropic enabling AI models to access local and remote data sources",
  },
  {
    id: "mcp-servers",
    name: "MCP Servers Registry",
    tagline: "Community-built MCP server collection",
    url: "https://github.com/modelcontextprotocol/servers",
    category: "mcp",
    tags: ["MCP", "open-source", "community"],
    free: true,
    highlight: "Official collection of reference MCP servers for GitHub, Slack, Postgres, filesystem, and more",
  },
  {
    id: "zapier-ai",
    name: "Zapier AI",
    tagline: "No-code automation with AI actions",
    url: "https://zapier.com/ai",
    category: "mcp",
    tags: ["no-code", "automation", "integrations"],
    free: false,
    highlight: "Connect Claude and other AI models to 6,000+ apps with no-code automation triggers",
  },
  {
    id: "make",
    name: "Make",
    tagline: "Visual automation platform with AI modules",
    url: "https://www.make.com",
    category: "mcp",
    tags: ["no-code", "automation", "visual"],
    free: true,
    highlight: "Drag-and-drop workflow builder with native Claude and OpenAI modules",
  },

  // ── Evals & Benchmarks ────────────────────────────────────────────────────
  {
    id: "lmarena",
    name: "LM Arena",
    tagline: "Crowdsourced model ranking via blind comparisons",
    url: "https://lmarena.ai",
    category: "evals",
    tags: ["benchmarks", "community", "ranking"],
    free: true,
    highlight: "Elo-based leaderboard from millions of human preference votes across all major models",
  },
  {
    id: "promptfoo",
    name: "Promptfoo",
    tagline: "Open-source LLM testing and red-teaming",
    url: "https://www.promptfoo.dev",
    category: "evals",
    tags: ["testing", "open-source", "red-teaming"],
    free: true,
    highlight: "YAML-based test suites for evaluating prompt quality, safety, and regression testing",
  },
  {
    id: "openai-evals",
    name: "OpenAI Evals",
    tagline: "Framework for evaluating LLM outputs",
    url: "https://github.com/openai/evals",
    category: "evals",
    tags: ["OpenAI", "open-source", "benchmarks"],
    free: true,
    highlight: "Systematic framework for measuring model performance with hundreds of pre-built evals",
  },
  {
    id: "helicone",
    name: "Helicone",
    tagline: "LLM observability and monitoring",
    url: "https://helicone.ai",
    category: "evals",
    tags: ["observability", "cost", "logging"],
    free: true,
    highlight: "One-line integration to log requests, track costs, and monitor latency across LLM providers",
  },

  // ── Communities ───────────────────────────────────────────────────────────
  {
    id: "huggingface-community",
    name: "Hugging Face",
    tagline: "The GitHub of machine learning",
    url: "https://huggingface.co",
    category: "communities",
    tags: ["community", "models", "datasets"],
    free: true,
    highlight: "Host, discover, and share ML models, datasets, and demos with 1M+ model repos",
  },
  {
    id: "reddit-ml",
    name: "r/MachineLearning",
    tagline: "Reddit's ML research community",
    url: "https://www.reddit.com/r/MachineLearning",
    category: "communities",
    tags: ["community", "research", "Reddit"],
    free: true,
    highlight: "Active discussion of papers, industry news, and research with 3M+ members",
  },
  {
    id: "ai-twitter",
    name: "AI on Twitter/X",
    tagline: "Real-time AI discourse",
    url: "https://x.com/search?q=%23AI&f=live",
    category: "communities",
    tags: ["community", "news", "social"],
    free: true,
    highlight: "Researchers, founders, and engineers sharing papers, demos, and takes as they happen",
  },
  {
    id: "alignment-forum",
    name: "AI Alignment Forum",
    tagline: "Technical AI safety research and discussion",
    url: "https://www.alignmentforum.org",
    category: "communities",
    tags: ["safety", "alignment", "research"],
    free: true,
    highlight: "Focused forum for long-form AI safety research posts from leading researchers",
  },

  // ── Research & Papers ─────────────────────────────────────────────────────
  {
    id: "arxiv-ai",
    name: "arXiv AI",
    tagline: "AI and ML preprint server",
    url: "https://arxiv.org/list/cs.AI/recent",
    category: "research",
    tags: ["papers", "research", "preprints"],
    free: true,
    highlight: "The primary venue for AI research papers before peer review — hundreds published daily",
  },
  {
    id: "papers-with-code",
    name: "Papers With Code",
    tagline: "ML papers linked to their code",
    url: "https://paperswithcode.com",
    category: "research",
    tags: ["papers", "code", "benchmarks"],
    free: true,
    highlight: "Every ML paper linked to its implementation, with live benchmark leaderboards",
  },
  {
    id: "the-gradient",
    name: "The Gradient",
    tagline: "Long-form ML research writing",
    url: "https://thegradient.pub",
    category: "research",
    tags: ["blog", "research", "writing"],
    free: true,
    highlight: "In-depth articles by researchers explaining complex ML concepts and recent advances",
  },
  {
    id: "anthropic-research",
    name: "Anthropic Research",
    tagline: "Anthropic's published AI safety research",
    url: "https://www.anthropic.com/research",
    category: "research",
    tags: ["Anthropic", "safety", "papers"],
    free: true,
    highlight: "Constitutional AI, interpretability, model cards, and frontier safety research from Anthropic",
  },
];
